### ISSUE TITLE
forRootAsync doesn't work in version 0.2.3

### ISSUE THREAD

**Issue by NilsLeger** [jmcdo29/nestjs-throttler#260]
Hello everyone,

**Problem**
I installed the latest version of the nestjs-throttler (0.2.3). 
forRootAsync did not work.

**Solution**
I installed version 0.2.2

**Conclusion**
Bug in version 0.2.3.

**Comment by jmcdo29** [comment]
Can you provide a minimum repreoduction?

**Comment by NilsLeger** [comment]
Error message is `Property 'forRootAsync' does not exist on type 'typeof ThrottlerModule'.`

Import in `app.module.ts`:
`ThrottlerModule.forRootAsync({
                imports: [ConfigModule],
                inject: [ConfigService],
                useFactory: (config: ConfigService) => ({
                  ttl: config.get('THROTTLE_TTL'),
                  limit: config.get('THROTTLE_LIMIT'),
                }),
              }),`

Which additional information do you need?

**Comment by jmcdo29** [comment]
Ah, it appears it got called `registerAsync` and not `forRootAsync`. Definitely a confusing DX. I can make a PR for this this evening and make a new release.

**Comment by NilsLeger** [comment]
I think `registerAsync` is allright as it is also used in other modules. You may just change the `README.md` because there it says `forRootAsync`. That's why I thought it is a bug.

Thank you very much for this greate module. It saved me a lot of time.

**Comment by jmcdo29** [comment]
Either way, I'd prefer to use consistent naming. Currently there is `forRoot` and `registerAsync`. I'll make a new release one way or another

**Comment by jmcdo29** [comment]
Should be fixed in 0.3.0. `forRootAsync` is now used instead of `registerAsync` to better align with the docs
